{
 "title": "Process_Network_Exporter进程详情",
 "description": "进程监控",
 "tags": [ "Process" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(process_uname_info{job=\"process-network\"},instance)"
   },
   {
    "name": "pid",
    "label": "pid",
    "query": "label_values(process_cpu_percent{instance=~\"$node\"},pid)"
   }
  ]
 },
 "panels": [
  {
   "title": "内存使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_memory_percent{instance=~\"$node\",pid=~\"$pid\"}"
    }
   ]
  },
  {
   "title": "CPU 总使用率 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_percent{instance=~\"$node\",pid=~\"$pid\",job=\"process-network\"})"
    }
   ]
  },
  {
   "title": "虚拟内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"vms\"}",
     "legendFormat": "vms"
    }
   ]
  },
  {
   "title": "驻留内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"rss\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "交换分区内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"swap\"}",
     "legendFormat": "swap"
    }
   ]
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 11, "x": 0, "y": 3 } },
  {
   "title": "内存情况汇总",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"vms\"}",
     "legendFormat": "虚拟内存总量"
    },
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"swap\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_info{instance=~\"$node\",pid=~\"$pid\",memtype=\"rss\"}",
     "legendFormat": "驻留内存"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",pid=~\"$pid\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "process_memory_info{job=\"process-network\",instance=~\"$node\",pid=~\"$pid\"}",
     "legendFormat": "内存剩余"
    }
   ]
  },
  {
   "title": "进程情况监测--Network",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg(process_network_info{job=\"process-network\",instance=~\"$node\",pid=~\"$pid\"}) by(cmd,src,dst,status,type,pid,uid)",
     "legendFormat": "Src"
    }
   ]
  }
 ]
}