{
 "title": "Lustre_OSS_1",
 "tags": [ "Lustre" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_uname_info{job=~\"lustre-exporter\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "总客户端列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSS 总客户端列表",
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 1 },
   "options": {
    "content": "<table>\n  <thead>\n  <tr style=\"color: #33a2e5;\">\n    <th>节点</th>\n    <th>快照时间</th>\n    <th>read_bytes</th>\n    <th>write_bytes</th>\n    <th>setattr</th>\n    <th>punch</th>\n    <th>statfs</th>\n    <th>preprw</th>\n    <th>commitrw</th>\n    <th>ping</th>\n  </tr>\n  </thead>\n  <tbody>\n  <tr>\n    <td>192.168.1.101</td>\n    <td>1597737495.421095324</td>\n    <td>41253</td>\n    <td>29851</td>\n    <td>3</td>\n    <td>106</td>\n    <td>106320</td>\n    <td>71104</td>\n    <td>71104</td>\n    <td>966</td>\n  </tr>\n  <tr>\n    <td>192.168.1.102</td>\n    <td>1597737495.421277314</td>\n    <td>51115</td>\n    <td>1922</td>\n    <td>6</td>\n    <td>32</td>\n    <td>106514</td>\n    <td>53037</td>\n    <td>53037</td>\n    <td>117</td>\n  </tr>\n  <tr>\n    <td>192.168.1.103</td>\n    <td>1597737495.421459684</td>\n    <td>40083</td>\n    <td>2682</td>\n    <td>4</td>\n    <td>274</td>\n    <td>106405</td>\n    <td>42765</td>\n    <td>42765</td>\n    <td>202</td>\n  </tr>\n  </tbody>\n</table>"
   }
  },
  { "title": "整体文件数量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">文件总数</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7;text-align: center\">34605430 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7;text-align: center\"></span>\n</div>"
   }
  },
  {
   "title": "OSS 文件总数",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": {
    "content": "<table>\n  <thead>\n  <tr style=\"color: #33a2e5;\">\n    <th>OSS节点名称</th>\n    <th>文件总数</th>\n  </tr>\n  </thead>\n  <tbody>\n  <tr>\n    <td>osd-zfs.sxu-OST0003</td>\n    <td>34605430</td>\n  </tr>\n  <tr>\n    <td>osd-zfs.sxu-OST0002</td>\n    <td>25605430</td>\n  </tr>\n  <tr>\n    <td>osd-zfs.sxu-OST0001</td>\n    <td>45005430</td>\n  </tr>\n  </tbody>\n</table>\n"
   }
  },
  { "title": "Node_Exporter信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU 总使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "交换分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} - node_filesystem_free_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"}) / node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} * 100"
    }
   ]
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 16, "y": 18 } },
  {
   "title": "Lustre Stat信息 - obdfilter.sxu-OST0003",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">read_bytes</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7;text-align: center\">3490912 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7;text-align: center\">bytes</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">write_bytes</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">1596249 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">bytes</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">destroy</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">64392 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">create</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">206 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">statfs</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">6777329 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">get_info</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">100 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">setattr</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">110650 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">punch</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">7849 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">connect</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">80 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">reconnect</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">42 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">disconnect</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">1 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">preprw</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">5087161 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">ping</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">106690 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">reqs</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 8, "y": 29 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">snapshot_time</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7;text-align: center\">1597489585.907338876 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7;text-align: center\">secs.nsecs</span>\n</div>"
   }
  }
 ]
}