{
 "title": "Lustre Dashboard1",
 "tags": [ "Lustre" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<h6></h6></br>\r\n<h6 style=\"text-align:center;font-size:20px;color:green\" >version information</h6>\r\n<h6 style=\"text-align:center;font-size:20px;color:green\">2.2.13</h6>\r\n"
   }
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 } },
  {
   "title": "MDS服务器状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info{nodename=\"MGS01\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "OSS服务器状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info{nodename!=\"MGS01\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "当前节点列表",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info)",
     "legendFormat": "总内存"
    }
   ]
  }
 ]
}