{
 "title": "Lustre_MDS_1",
 "tags": [ "Lustre" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_uname_info{job=~\"lustre-exporter\"},instance)"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lustre Stat信息 - obdfilter.sxu-MGS01",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU 总使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "交换分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} - node_filesystem_free_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"}) / node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "当前并发用户数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])%400)* on (instance) group_left (nodename) (node_uname_info{nodename=\"MGS01\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "当前并发总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_TCP_inuse{}) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "整体网络吞吐量(IB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_infiniband_port_data_received_bytes_total{device!=\"lo\"}[5m])*8)+avg(irate(node_infiniband_port_data_transmitted_bytes_total{device!=\"lo\"}[5m])*8)"
    }
   ]
  },
  {
   "title": "当前容量",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance,device) (node_filesystem_size_bytes{ job=\"lustre-exporter\" ,fstype=~\"ext4|xfs\",instance=~\"$node\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "服务器资源总览表(每页10行)",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"lustre-exporter\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"lustre-exporter\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"lustre-exporter\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"lustre-exporter\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"lustre-exporter\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"lustre-exporter\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"lustre-exporter\"} / (node_memory_MemTotal_bytes{job=~\"lustre-exporter\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"lustre-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"lustre-exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"lustre-exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"lustre-exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"lustre-exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=~\"lustre-exporter\"}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=~\"lustre-exporter\"}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"lustre-exporter\"}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"lustre-exporter\"}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "当前节点列表",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info)",
     "legendFormat": "总内存"
    }
   ]
  }
 ]
}