{
 "title": "Alerts",
 "description": "Monitor and set alerts for all the pings to your servers using blackbox exporter and prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "告警记录", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "警告",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "severity=warning", "labelSelector": "*", "target": "Query", "type": "timeserie" }
   ]
  },
  {
   "title": "严重",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "severity=critical", "labelSelector": "*", "target": "Query", "type": "timeserie" }
   ]
  },
  {
   "title": "实时告警列表",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "labelSelector": "time,dc,instance,alertname,description",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "告警历史",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "24小时告警历史",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "ALERTS{alertstate='firing'}[24h]",
       "labelSelector": "*",
       "target": "Query",
       "type": "timeserie"
      }
     ]
    }
   ]
  }
 ]
}