{
 "title": "Host IPMI",
 "description": "Dashboard IPMI",
 "tags": [ "IPMI" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "label_values(ipmi_up,host)" }
  ]
 },
 "panels": [
  {
   "title": "scrape Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_up{host=\"$host\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Fan DutyCycle of $host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "repeat": "ChassisMessage",
   "yaxes": [
    { "format": "percent", "label": "DutyCycle(%)" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_value{host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature of $host",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature(℃)" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}