{
 "title": "IPMI dashboard",
 "tags": [ "IPMI" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "<h1></h1></br>\r\n<h1 style=\"text-align:center;font-size:50px;color:green\" >高性能计算中心</h1>\r\n<center>For more information help：<a href=\"http://hpc.sxu.edu.cn/\" style=\"display:inline-block; text-align:center\">hpc/sxu</a>"
   }
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "Current_Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt", "label": "Watts(w)" }
   ],
   "targets": [
    { "expr": "sum(ipmi_power_watts)" }
   ]
  },
  {
   "title": "ipmimonitoring scrape Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_up{collector=\"ipmimonitoring\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IPMI Power Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_power_state", "legendFormat": "{{host}}" }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}