{
 "title": "Node_Exporter_单台展示",
 "description": "【中文版本】2020.06.28更新，增加整体资源展示！支持 Grafana6&7，Node Exporter v0.16及以上的版本，优化重要指标展示。包含整体资源展示与资源明细图表：CPU 内存 磁盘 IO 网络等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "网卡",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "hostip",
    "label": "HOSTIP",
    "query": "label_values( node_uname_info,instance)"
   }
  ]
 },
 "panels": [
  { "title": "资源明细：【$show_hostname】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 } },
  {
   "title": "$node-CPU情况",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$node\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$node\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "avg(up{job=\"node-exporter\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "节点是否存活"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system',instance=~\"$node\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "100 - ( avg(  irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\",instance=~\"$node\"}[5m])  )  by (instance) * 100   )",
     "legendFormat": "CPU总使用率"
    },
    {
     "expr": " avg(  irate(node_cpu_seconds_total{mode=\"user\",instance=~\"$node\"}[5m])  )  by (instance) * 100 ",
     "legendFormat": "CPU用户使用率"
    },
    {
     "expr": " avg(  irate(node_cpu_seconds_total{job=~\"$job\",mode=\"system\",instance=~\"$node\"}[5m])  )  by (instance) * 100   ",
     "legendFormat": "CPU系统使用率"
    },
    {
     "expr": "(avg by (environment,instance) (irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\",instance=~\"$node\"}[5m])))  * 100",
     "legendFormat": "CPU空闲使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"iowait\",instance=~\"$node\"}[5m])) by(instance) * 100",
     "legendFormat": "CPU iowait"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=~\"softirq|nice|irq|steal\",instance=~\"$node\"}[5m])) by(instance) * 100",
     "legendFormat": "CPU other使用率"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15分钟负载"
    }
   ]
  },
  {
   "title": "CPU 总使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "最大分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} - node_filesystem_free_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"}) / node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\",instance=~\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "交换分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100"
    }
   ]
  },
  {
   "title": "内存情况汇总",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"}) by (instance)",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\"$node\"} - node_memory_MemFree_bytes{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "已使用内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\"$node\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "实际使用内存量"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "剩余内存"
    },
    {
     "expr": "(1-(node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=~\"$node\"} / (node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\"$node\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "((node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=~\"$node\"} / (node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\"$node\"})))* 100",
     "legendFormat": "内存剩余"
    }
   ]
  },
  {
   "title": "磁盘总量",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (instance,device) (node_filesystem_size_bytes{ job=~\"$job\" ,fstype=~\"ext4|xfs\",instance=~\"$node\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率(每页10行)",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(node_uname_info{instance=~\"$node\"} ) by(nodename,instance)-0",
     "legendFormat": "主机名"
    },
    {
     "expr": "avg(irate(node_disk_reads_completed_total{job=\"node-exporter\",instance=~\"$node\"}[5m]))by(instance,device)",
     "legendFormat": "磁盘读取速率"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node-exporter\",instance=~\"$node\"}[5m])",
     "legendFormat": "磁盘写入速率"
    },
    {
     "expr": "(irate(node_disk_written_bytes_total{job=\"node-exporter\",instance=~\"$node\"}[1m]))/1024/1024",
     "legendFormat": "设备读取MB速率"
    },
    {
     "expr": "(irate(node_disk_read_bytes_total{job=\"node-exporter\",instance=~\"$node\"}[1m]))/1024/1024",
     "legendFormat": "设备写入MB速率"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "文件系统情况汇总",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "avg(node_filefd_allocated{job=\"node-exporter\",instance=~\"$node\"}) by (instance)"
    },
    {
     "expr": "avg(node_filefd_allocated{job=\"node-exporter\",instance=~\"$node\"})by (instance) /avg(node_filefd_maximum{job=\"node-exporter\",instance=~\"$node\"}) by (instance) * 100 "
    },
    {
     "expr": "avg(node_filesystem_files_free{mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\",instance=~\"$node\"}) by (instance)"
    }
   ]
  },
  {
   "title": "节点的inode的剩余可用的百分比",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 -node_filesystem_files_free{job=\"node-exporter\",fstype=~\"ext4|xfs\",instance=~\"$node\"} / node_filesystem_files{job=\"node-exporter\",fstype=~\"ext4|xfs\",instance=~\"$node\"}) * 100  ",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "下载带宽",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 55 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$node\"}[5m])*8) by (instance)"
    }
   ]
  },
  {
   "title": "上传带宽",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 55 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$node\"}[5m])*8) by (instance)"
    }
   ]
  },
  {
   "title": "ESTABLIASHED连接数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{job=~\"$job\", state=\"established\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "网络情况汇总(每页10行)",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$node\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_receive_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒接收比特数"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_transmit_bytes_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒发送的比特数"
    },
    {
     "expr": "sum by (environment,instance) (node_tcp_connection_states{job=~\"$job\",instance=~\"$node\"})",
     "legendFormat": "TCP连接总数"
    },
    {
     "expr": "\r\n((node_network_transmit_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}+node_network_receive_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"})/ node_network_transmit_packets_total{instance=~\"$node\"} )*100",
     "legendFormat": "established连接数"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_receive_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒接包量"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_transmit_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒发包量"
    },
    {
     "expr": "\n((node_network_transmit_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}+node_network_receive_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"})/ node_network_transmit_packets_total{instance=~\"$node\"} )*100"
    },
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])",
     "legendFormat": "IB下载速率"
    },
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])",
     "legendFormat": "IB上传速率"
    }
   ]
  },
  {
   "title": "网络上传带宽(TCP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$node\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "网络下载带宽(TCP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$node\"}[5m])*8) by (instance)",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    }
   ]
  },
  {
   "title": "丢包率(TCP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(node_netstat_Icmp_OutMsgs{instance=~\"$node\"}[5m]) ) / sum(increase(node_network_transmit_packets_total{instance=~\"$node\"}[5m]) ) )*100",
     "legendFormat": "丢包率"
    }
   ]
  },
  {
   "title": "网络上传带宽(IB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "网络下载带宽(IB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 74 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    }
   ]
  }
 ]
}