{
 "title": "Outdoor machine dashboard",
 "tags": [ "SNMP" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "OMHost", "query": "label_values(snmp_up,host)" }
  ]
 },
 "panels": [
  {
   "title": "Pump stat",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "snmp_oid_number{metric=~\"Pump*\",metric!~\"suction\",host=\"$host\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snmp_oid_number{metric=\"amb-temp\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Pump suction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snmp_oid_number{metric=~\"Pump-suction\",host=\"$host\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "temp stat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snmp_oid_number{metric=~\"temp\",metric!~\"amb*\",host=\"$host\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 } }
 ]
}