{
 "title": "Lustre_MDS_2",
 "tags": [
  "Lustre",
  "MDS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机地址",
    "query": "label_values(node_uname_info{job=~\"lustre-exporter\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "当前节点列表",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info)",
     "legendFormat": "总内存"
    }
   ]
  },
  { "title": "节点基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU 总使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率 ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    },
    {}
   ]
  },
  {
   "title": "交换分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100"
    }
   ]
  },
  {
   "title": "当前并发用户数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])%400)* on (instance) group_left (nodename) (node_uname_info{nodename=\"MGS01\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "当前并发总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_sockstat_TCP_inuse{}) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 } },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "网络情况汇总(每页10行)",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$node\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_receive_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒接收比特数"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_transmit_bytes_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒发送的比特数"
    },
    {
     "expr": "sum by (environment,instance) (node_tcp_connection_states{job=\"node-exporter\",instance=~\"$node\"})",
     "legendFormat": "TCP连接总数"
    },
    {
     "expr": "\r\n((node_network_transmit_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}+node_network_receive_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"})/ node_network_transmit_packets_total{instance=~\"$node\"} )*100",
     "legendFormat": "established连接数"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_receive_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒接包量"
    },
    {
     "expr": "avg by (environment,instance,device) (irate(node_network_transmit_packets_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}[1m]))",
     "legendFormat": "每秒发包量"
    },
    {
     "expr": "\n((node_network_transmit_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"}+node_network_receive_errs_total{device=~\"eth0|eth1|ens33|ens37|mlx4_0\",instance=~\"$node\"})/ node_network_transmit_packets_total{instance=~\"$node\"} )*100"
    },
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])",
     "legendFormat": "IB下载速率"
    },
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])",
     "legendFormat": "IB上传速率"
    }
   ]
  },
  {
   "title": "网络上传带宽(IB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "网络下载带宽(IB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{device=~\"mlx4_0\",instance=~\"$node\",port=\"1\"}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    }
   ]
  }
 ]
}