{
 "title": "Lustre DashBoard2",
 "tags": [ "Lustre" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "MDS 服务器状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MDS服务器状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info{nodename=\"MGS01\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "当前时钟", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 16, "x": 4, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<h6 style=\"font-size: 14px;color: #464C54;text-align: center\">Lustre版本</h6>\n<div style=\"text-align: center\">\n  <span style=\"font-size: 30.400000000000002px;color: #32AC2DF7\">2.2.13 </span>\n  <span style=\"font-size: 15.400000000000002px;;color: #32AC2DF7\">ver</span>\n</div>"
   }
  },
  {
   "title": "总文件描述符",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"192.168.1.245:9100\"})"
    }
   ]
  },
  {
   "title": "总连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_tcp_connection_states{instance=\"192.168.1.245:9100\",job=\"lustre-exporter\"})"
    }
   ]
  },
  {
   "title": "【Lustre】：各分区可用空间(EXT.*/XFS)",
   "type": "table-old",
   "description": "本看板中的：磁盘总量、使用量、可用量、使用率保持和df命令的Size、Used、Avail、Use% 列的值一致，并且Use%的值会四舍五入保留一位小数，会更加准确。\n\n注：df中Use%算法为：(size - free) * 100 / (avail + (size - free))，结果是整除则为该值，非整除则为该值+1，结果的单位是%。\n参考df命令源码：",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"192.168.1.245:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  { "title": "OSS 服务器状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "当前节点列表",
   "type": "table-old",
   "description": "点击IP查看OSS服务器状态",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "( up{job=\"lustre-exporter\"}  ) * on (instance) group_left (nodename) (node_uname_info{nodename=~\"OSS*\"})",
     "legendFormat": "总内存"
    }
   ]
  }
 ]
}